// frontend/rfpmvue/src/App.vue
<template>
  <div id="app">
    <RFPMAppComponent>
      <template slot="menuContentTemplate" slot-scope="slotProps">
        <MenuItemComponent v-if="slotProps.app.logged" :label="i18n('rfpm.menu.masters')">
          <template slot="menuItemContentTemplate">
            <MenuItemComponent
              :label="i18n('rfpm.menu.notes')"
              :level="1"
              :componentView="'Note'"
              :module="'Masters'"
            />
            <MenuItemComponent
              v-if="getExtraData('App').isAdmin()"
              :label="i18n('rfpm.menu.proyects')"
              :level="1"
              :componentView="'Proyect'"
              :module="'Masters'"
            />
            <MenuItemComponent
              v-if="getExtraData('App').isAdmin()"
              :label="i18n('rfpm.menu.tags')"
              :level="1"
              :componentView="'Tag'"
              :module="'Masters'"
            />
            <MenuItemComponent
              :label="i18n('rfpm.menu.wiki')"
              :level="1"
              :componentView="'Wiki'"
              :module="'Masters'"
            />
          </template>
        </MenuItemComponent>
        <MenuItemComponent :label="i18n('rfpm.menu.security')" v-if="getExtraData('App').isAdmin()">
          <template slot="menuItemContentTemplate">
            <MenuItemComponent
              v-if="getExtraData('App').isAdmin()"
              :label="i18n('rfpm.menu.roles')"
              :level="1"
              :componentView="'Role'"
              :module="'Masters'"
            />
            <MenuItemComponent
              v-if="getExtraData('App').isAdmin()"
              :label="i18n('rfpm.menu.users')"
              :level="1"
              :componentView="'User'"
              :module="'Masters'"
            />
          </template>
        </MenuItemComponent>
      </template>
    </RFPMAppComponent>
  </div>
</template>

<script>
import RFPMAppComponent from "./components/rfpm/components/RFPMAppComponent";
import MenuItemComponent from "./components/rfvue/components/menuitem/MenuItemComponent";
import BaseComponent from "./components/rfvue/components/base/BaseComponent";

export default {
  extends: BaseComponent,
  name: "App",
  components: {
    RFPMAppComponent,
    MenuItemComponent
  }
};
</script>

// frontend/rfpm/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'rfpm';
}

<rf-app [fnPostLogin]="this.functionPostLogin">

  <ng-template rfTemplate="headerLeft" let-appContext="appContext">
    <div class="RfpmTitle">
      {{"RFPM"}}
    </div>
  </ng-template>

  <ng-template rfTemplate="headerBody" let-appContext="appContext">
    <div class="RfpmUser">
      {{'rfng.user' | i18n}}: <a (click)="this.clickUser()">{{this.appService.getNickUser()}}</a>
    </div>
  </ng-template>

  <ng-template rfTemplate="menuContent" let-appContext="appContext">

    <ng-container *ngIf="this.appService.isAdmin()">

      <rf-menuitem label="{{'rfpm.menu.security' | i18n}}">

        <ng-template rfTemplate="menuItemContent">
          <rf-menuitem label="{{'rfpm.menu.users' | i18n}}" [level]="1" componentView="UserComponent" module="Security">
          </rf-menuitem>
        </ng-template>

      </rf-menuitem>

    </ng-container>

    <rf-menuitem label="{{'rfpm.menu.masters' | i18n}}">

      <ng-template rfTemplate="menuItemContent">

        <rf-menuitem label="{{'rfpm.menu.notes' | i18n}}" [level]="1" componentView="NoteComponent" module="Masters">
        </rf-menuitem>

        <ng-container *ngIf="this.appService.isAdmin()">
          <rf-menuitem label="{{'rfpm.menu.proyects' | i18n}}" [level]="1" componentView="ProyectComponent"
            module="Masters">
          </rf-menuitem>
        </ng-container>

        <rf-menuitem label="{{'rfpm.menu.wiki' | i18n}}" [level]="1" componentView="WikiComponent" module="Masters">
        </rf-menuitem>

        <ng-container *ngIf="this.appService.isAdmin()">
          <rf-menuitem label="{{'rfpm.menu.tags' | i18n}}" [level]="1" componentView="TagComponent" module="Masters">
          </rf-menuitem>
        </ng-container>

      </ng-template>

    </rf-menuitem>

  </ng-template>

</rf-app>
